create table if not exists public.environmental_data (
  id bigint generated by default as identity primary key,
  company text not null,
  ticker text not null,
  reporting_year integer not null,
  scope_1 numeric,
  scope_2_market numeric,
  scope_2_location numeric,
  scope_3 numeric,
  unit text not null default 'tCO2e',
  source_name text not null,
  source_url text not null,
  source_type text not null check (source_type in ('company-report','bmv','climate-trace')),
  created_at timestamptz not null default now(),
  unique (ticker, reporting_year, source_type)
);

-- GREENInvest source policy:
-- 1. Prefer official annual/sustainability reports for displayed company emissions.
-- 2. Use BMV IFRS S1/S2 disclosures to cross-check standardized figures when available.
-- 3. Keep Climate TRACE separate as an independent reference because boundaries can differ.
