create table if not exists public.research_outputs (
  id bigint generated by default as identity primary key,
  research_query text not null,
  research_summary text not null,
  created_at timestamptz not null default now()
);

alter table public.research_outputs enable row level security;

create policy "Public can read research outputs"
on public.research_outputs for select
to anon
using (true);

create policy "Public can insert research outputs"
on public.research_outputs for insert
to anon
with check (true);
